# not used so far
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tfcontrolled-actuator_controller
  labels:
    run: tfcontrolled
spec:
  selector:
    matchLabels:
      name: tfcontrolled
  template:
    metadata:
      labels:
        name: tfcontrolled
    spec:
      containers:
      - name: tfcontrolled-actuator_controller
        image: tfcontrolled/actuator_controller
        # command: ['docker', 'run', '-p', '80:80', 'httpd:latest']
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /var/run
            name: docker-sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run