# the TF Serving endpoint
endpoints_benchmark: ["http://localhost:8000"]
endpoint_profiler: "http://192.168.99.108:30001"
# bench_data folder
bench_folder: "bench_data"
# validation_data folder
validation_folder: "validation_data"
# the number of times needed to repeat the response time measure
repeat_measure: 3
# the number of requests needed to warm up the model
warm_up_times: 2
# requests_store endpoint
requests_store: "http://localhost:5002"

single_stream:
  duration: 1024
  samples_per_query: 1
  tail: 0.9

server:
  # the lambda of the Poisson distribution [s]
  lambda_p: 10
  # number of samples per query
  samples_per_query: 1
  # number of requests per second
  reqs_per_s: 10
  # repeat the sending for repeat times
  repeat: 50