models:
  - name: "half_plus_two"
    version: 1
    sla: 1
    alpha: 1
  - name: "half_plus_three"
    version: 1
    sla: 0.5
    alpha: 1
  - name: "resnet_NHWC"
    version: 1
    sla: 0.5
    alpha: 1
containers:
  - model: "half_plus_two"
    version: 1
    container: "tfserving-rest-cpu-0"
    active: true
    device: 0
    node: "192.168.99.105"
    port: 30001
    quota: 100000
  - model: "half_plus_three"
    version: 1
    container: "tfserving-rest-cpu-1"
    active: true
    device: 0
    node: "192.168.99.105"
    port: 30002
    quota: 100000
  - model: "resnet_NHWC"
    version: 1
    container: "tfserving-rest-cpu-2"
    active: true
    device: 0
    node: "192.168.99.105"
    port: 30003
    quota: 100000
  - model: "all"
    version: 1
    container: "tfserving-rest-gpu-0"
    active: true
    device: 1
    node: "192.168.99.105"
    port: 30004
    quota: 100000