models:
  - name: "resnet_NHWC"
    version: 1
    sla: 0.5
    alpha: 0.5
    profiled_rt: 0.15
containers:
  # node 1, NV6-1: 10.0.0.4 | 10.244.1.15
  - model: "resnet_NHWC"
    version: 1
    container: "tfserving-rest-cpu-4"
    active: true
    device: 0
    node: "10.244.1.15"
    port: 8504
    quota: 100000
  - model: "all"
    version: 1
    container: "tfserving-rest-gpu-1"
    active: false
    device: 1
    node: "10.244.1.15"
    port: 8601
    quota: 100000
  # node 2, NV6-2: 10.0.0.5 | 10.244.2.10
  - model: "resnet_NHWC"
    version: 1
    container: "tfserving-rest-cpu-4"
    active: true
    device: 0
    node: "10.244.2.10"
    port: 8504
    quota: 100000
  - model: "all"
    version: 1
    container: "tfserving-rest-gpu-1"
    active: false
    device: 1
    node: "10.244.2.10"
    port: 8601
    quota: 100000